---
title: Perfect Fit
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  strips:
    title: Strips
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
tagline: Improving the way developers and planners assess parking demand
background-image: "/uploads/16598201447_397e2a30b4_z.jpg"
description: |-
  ## USING REAL DATA TO HELP COMMUNITIES ESTABLISH INFORMED, SUSTAINABLE, AND ECONOMICAL PARKING POLICIES

  Parking is a point of contention in communities across Metro Boston, yet many deliberations about the topic occur in the absence of hard data about how much parking we have, and how much we need. The Metropolitan Area Planning Council (MAPC) has begun a multi-phase initiative to develop the data and tools that communities need to establish
  informed, sustainable, and economical parking policies.

  In Phase 1, MAPC conducted middle-of-the-night surveys at 80 multifamily residential developments to measure how much parking was actually being used during the hours when most people are at home and asleep. We also began to model the factors that best predict parking demand. Surveys were conducted in Arlington, Chelsea, Everett, Malden, and Melrose.

  In the next phase, MAPC will collect data in Boston, Cambridge, and other nearby communities to create a broader sample and more robust statistical results. Ultimately, we plan to create online tools to support community decision-making about parking requirements.
links-body: |-
  ## Links

  * Executive Summary
  * Full Report
  * Technical Appendix
  * Powerpoint Presentation
permalink: pretty
